name: Baseball435sSpells
author: baseball435
version: 1.0
description: Spells you can use while in mini games!
main: com.baseball435.spells.Main
commands:
     spells:
           description: Gives you an options of spell commands
     class:
           description: Gives you an options of class commands
